#### TASK1

1. Exception 包括RuntimeException（由编程错误导致的异常）      FileNotFoundException（找不到文件）  ，其中RuntimeException又包括几个常见的（NullPointerException访问了空指针   ArithmeticException ArrayIndexOutOfBoundsException数组索引越界，试图访问数组中不存在的元素   ClassCastException类型转换异常（一般是向下转型出错），   NumberFormatException无法将一个字符串解析为合适的数值类型)

   处理态度：1.完善代码，避免出现异常（如输入的时候先检测除数是否为0）2.捕获这些异常并提供错误信息，保证其不影响后续程序的执行

   

2. Error包括StackOverflowError（递归太深等因素导致栈的空间耗尽）  OutOfMemoryError（JVM没有足够的内存分配给新的对象）等。

   处理态度：1.完善代码防止此类错误发生。2.直接终止程序

3. Java将所有派生于Error类或者RunTimeException类的异常称为非检查型（unchecked）异常，其他的就是检查型（check）异常。

   check异常：编译器强制要求处理，否则编译不通过。常见的有IOException(输入输出异常，有可能是尝试读取一个不存在的文件)。

   unchecked异常：通常由编程错误引起，不需要强制处理。通常为RunTimeException（如：ArrayIndexOutOfBoundsException数组索引越界），在编译的时候会通过。运行的时候出现异常就会往上一层的调用抛出（throw）上一层不处理就会继续往上，直到最上面的虚拟机JVM接收到异常，然后输出异常信息，退出程序。



#### TASK2

3. ```java
   class InsufficientFundsException extends Exception {//继承自Exception，所以该异常必须处理才能抛出成功
       public InsufficientFundsException(String message) {//构造器
           super(message);//自定义异常，传入想输出的异常信息。
       }
   }
   
   class BankAccount {
       private double balance;
   
       public BankAccount(double initialBalance) {
           this.balance = initialBalance;//传入账户的初始余额
       }
   
       public double getBalance() {
           return balance;
       }
   
       public void withdraw(double amount) throws InsufficientFundsException {
           //因为自定义的InsufficientFundsException是编译的异常，需要抛出给上一层或者捕获处理，所以要throws
           if (amount > balance) {
               throw new InsufficientFundsException("余额不足，无法取款。当前余额: " + balance);
               //如果钱不够就抛出InsufficientFundsException到调用该方法的位置,内容是"余额不足，无法取款。当前余额: " + balance
           }
           balance -= amount;
           //如果够钱就减去取出的钱；
       }
   }
   
   public class BankAccountExample {
       public static void main(String[] args) {
           BankAccount account = new BankAccount(Math.random()*200);
           //随机生成一个0~200的数作为账户的初始余额
           try {
               System.out.println("当前余额: " + account.getBalance());
               account.withdraw(150.0);//取150元，进入withdraw方法
               //如果withdraw方法抛出异常，那么就不会执行下面取款成功的语句，直接被捕获（进入catch语句）
               //如果没有抛出异常，那么输出取款成功，跳过catch语句，输出程序结束。
               System.out.println("取款成功。");
           } catch (InsufficientFundsException e) {//实例化一个InsufficientFundsException对象捕获withdraw的异常,并输出错误的信息
               System.err.println("错误: " + e.getMessage());
               //e.getMessage()就是访问上面传入的message;
               //奇怪的问题：如果把err换成out,那么程序结束就最后输出，但是如果是err，那么是错误的信息最后输出。
           }
   
           System.out.println("程序结束");
       }
   }
   ```



4.见文件夹java07Code

